Refactoring Awesome Books using ES6
tasnimchy96/awesome-books-es6 pull request #1
Opened 2023-05-05 21:26 UTC by tasnimchy96

In this branch i did:

- Used ES6 modules to write modular JavaScript.
- Refactored your functions to arrow functions.
- Displayed the current date below the navigation bar using Luxon Library.
- Divided your code into modules.

2023-05-05 21:51 UTC, Rustamxon7 reviewed
Hi @tasnimchy96, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that did not use the correct Gitflow. In this milestone, students were encouraged to use [Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), instead of [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md). Kindly fix the issue and resubmit your code again. Thank you!

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-05 21:58 UTC, tasnimchy96 commented
@Rustamxon7 Can you please give me a hint how should i fix it?

2023-05-05 22:11 UTC, Rustamxon7 commented
This [link](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) explains how to create Gitflow. You can look through and learn about it.

2023-05-05 22:41 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @tasnimchy96 :wave:  

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Professional pull request
✔️ Correct GitHub-flow
✔️ Linter checks are passing

## Required Changes ♻️

***Please kindly check the comments below.***

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 22:41 UTC, Tufahel commented on README.md
> +This project is [MIT](./LICENSE.md) licensed.
![image](https://user-images.githubusercontent.com/60083437/236580386-00264dca-b458-42e4-ab5d-6430c91c28fd.png)

- [ ] `LICENSE.md` link is not working. Kindly add it correctly. Every link you have added in the readme file should work as per the requirement of a professional readme.

2023-05-06 00:09 UTC, divinecharlotte approved these changes
# Hello @tasnimchy96    😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯

- Descriptive pr👍 
- linters are passing 👍 






## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 00:15 UTC, merged